version: "3.8"
services:
  butt:
    image: ghcr.io/hammady/butt:${BUTT_VERSION}
    environment:
      BUTT_SERVER_NAME: MyServer
      BUTT_SERVER_TYPE: 0
      BUTT_SERVER_ADDRESS: us2.internet-radio.com
      BUTT_SERVER_PORT: 8164
      BUTT_SERVER_PASSWORD: REDACTED
      BUTT_DEVICE_ID: 1
      BUTT_SAMPLE_RATE: 44100
      BUTT_BITRATE: 64
      BUTT_CHANNELS: 1
      BUTT_CODEC: mp3
      BUTT_SILENCE_LEVEL: 54.000000
      BUTT_SIGNAL_LEVEL: 52.000000
    volumes:
      - $HOME/butt:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/snd
    ports:
      - 1256:1256
    deploy:
      replicas: 1
  prayer-scheduler:
    image: ghcr.io/hammady/prayer-scheduler:0.1.0
    environment:
      FULL_CSV_URL: ${prayer-scheduler.full_csv_url}
      HEADER_CSV_URL: ${prayer-scheduler.header_csv_url}
      THRESHOLDS_CSV_URL: ${prayer-scheduler.thresholds_csv_url}
      DATE_FORMAT: ${prayer-scheduler.date_format}
      TIME_FORMAT: ${prayer-scheduler.time_format}
      CSV_REQUESTER_USER_AGENT: ${prayer-scheduler.csv_requester_user_agent}
      BUTT_SERVER_IP: ${prayer-scheduler.butt_server_ip}
      BUTT_SERVER_PORT: ${prayer-scheduler.butt_server_port}
    deploy:
      replicas: ${prayer-scheduler.replicas}
  stream-watcher:
    image: ghcr.io/hammady/stream-watcher:0.1.0
    environment:
      STREAM_METADATA_URL: ${stream-watcher.stream_metadata_url}
      WATCH_SLEEP_TIME_SECONDS: ${stream-watcher.watch_sleep_time_seconds}
      EXIT_AFTER_SLEEP_COUNT: ${stream-watcher.exit_after_sleep_count}
      TRACK_JSON_PATH: ${stream-watcher.track_json_path}
      TRACK_MATCH_STRING: ${stream-watcher.track_match_string}
      SMTP_HOST: ${stream-watcher.smtp_host}
      SMTP_PORT: ${stream-watcher.smtp_port}
      SMTP_TLS: ${stream-watcher.smtp_tls}
      SMTP_USERNAME: ${stream-watcher.smtp_username}
      SMTP_PASSWORD: ${stream-watcher.smtp_password}
      SMTP_FROM_ADDR: ${stream-watcher.smtp_from_addr}
      SMTP_TO_ADDR: ${stream-watcher.smtp_to_addr}
    deploy:
      replicas: ${stream-watcher.replicas}
  companion:
    image: ghcr.io/hammady/companion:beta-butt-0.1.34
    volumes:
      - companion-config:/companion
    ports:
      - "8000:8000"
    deploy:
      replicas: ${companion.replicas}
  filebrowser:
    image: filebrowser/filebrowser:latest
    volumes:
      - /${filebrowser.server_path}:/srv
      - /${filebrowser.database_path}:/database.db
    ports:
      - "${filebrowser.port}:80"
    user: ${filebrowser.user}
    deploy:
      replicas: ${filebrowser.replicas}
volumes:
  companion-config:
    driver: local
